### ISSUE TITLE
xbacklight is lacking support and prevalence

### ISSUE THREAD

**Issue by quentincaffeino** [superRaptor911/2020#1]
There are several problems with xbacklight, see [notes](https://wiki.archlinux.org/index.php/Backlight#xbacklight).

Maybe switch to another [alternative](https://wiki.archlinux.org/index.php/Backlight#Backlight_utilities)?
[Light](https://github.com/haikarainen/light) seems like a worthy replacement.

**Comment by superRaptor911** [comment]
Ok thanks, there are several problems with xbacklight and I will try Light
